name: 'Terraform Deployment on Azure'

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform Deployment on Azure'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # ✅ Authenticate with Azure using AZURE_CREDENTIALS secret
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # ✅ Initialize Terraform (Includes Modules)
    - name: Initialize Terraform with Modules
      run: terraform init -reconfigure
      working-directory: ./env/dev # ✅ Set working directory

    # ✅ Validate Terraform Configuration
    - name: Validate Terraform Configuration
      run: terraform validate
      working-directory: ./env/dev  # ✅ Set working directory

    # ✅ Format Check
    - name: Terraform Format Check
      run: terraform fmt -check
      working-directory: ./env/dev  # ✅ Set working directory

    # ✅ Generate Terraform Plan
    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan
      working-directory: ./env/dev  # ✅ Set working directory

    # ✅ Apply Terraform (if plan exists)
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./env/dev  # ✅ Set working directory
